### PR TITLE
PROPS Coin info

### PR DESCRIPTION
**Pull request by neethu-satheesh-s**
Hi, Could you please add PROPS coin info to hippo list? Thank you.

### CODE REVIEW

**Review by movekevin — COMMENTED** [review]
Can you add PROPS directly to the different lists here?

**Comment by neethu-satheesh-s** [comment]
@movekevin  Hi Kevin, I updated all the lists, could you please check if its all good and merge if so? Thank you.

**Comment by neethu-satheesh-s** [comment]
Hi, I am merging this.

**Review by movekevin — APPROVED** [review]
Can you make sure the unique index is indeed unique? 10 seems like it might have been taken

**Pull request merged**
