### PR TITLE
Add Shit Swap token

### PR DESCRIPTION
**Pull request by shitswap**
Add SHIT to token list

### CODE REVIEW

**Comment by Manahip** [comment]
let's merge when you launch on mainnet!

**Comment by shitswap** [comment]
we are launched already sir

**Comment by shitswap** [comment]
oh you mean our site?

yeah thats coming this week!

**Comment by shitswap** [comment]
Just so I understand, you basically want to make sure we are legit before approving PR?

**Comment by Manahip** [comment]
Just trying to avoid land grabbing! Otherwise someone could register all the coins from AAAA to ZZZZ.

**Comment by shitswap** [comment]
Hey

> Just trying to avoid land grabbing! Otherwise someone could register all the coins from AAAA to ZZZZ.

We are now live on Mainnet with our dex. Are you able to confirm the PR?

https://aptoshit.com

**Pull request closed without merging**
